### ISSUE TITLE
Update docs SDK examples/guides

### ISSUE THREAD

**Issue by johngrantuk** [balancer/b-sdk#339]
Once we have more stable codebase (mainly around permit/permit2) we need to update docs examples/guides to use most recent SDK interfaces.

**Comment by MattPereira** [comment]
Some realizations:

- Permit2 examples will require a `process.env.PRIVATE_KEY` in order to `.signTypedData`
- Should we have seperate `swapV2` and `swapV3` examples since only v3 uses permit2?
- Permit2 examples will have to be on Sepolia cus that's the only chain Router is deployed
- The token pair from scaffold prod does not get picked up by SOR paths fetched from API

**Comment by johngrantuk** [comment]
Thinking about this a bit more how about these separate examples as a fresh approach?

- How to fetch a swap
  - Fetches from api and shows how to re-query
  - No build call
- Swap With Approvals
  - Run on a fork (similar to removeLiquidity example)
  - Info at top explaining this is only way V2 works, mention signature alternative for V3
  - Not using API - use a hard coded V2 path
  - Approval process goes through function exported from separate example (see below)
  - use buildCall
- Swap With Signature
  - Run on a fork (similar to removeLiquidity example)
  - Info at top explaining this is V3 only and why Permit2/Signatures can be used
  - Not using API - use a hard coded path
  - Approval process goes through function exported from separate example (see below)
  - use buildCallWithPermit2
- Approvals
  - Shows the various methods of approving for V2/V3:
    - V2 approves vault
    - V3 with normal approvals, approve permit2, approve router
    - V3 with signature, approve permit2, signature
  - Exports each method as a function that can be used in other examples

**Comment by MattPereira** [comment]
Looks like the approvals are currently being abstracted away in `makeForkTx > forkSetup > approveTokens`. 

We want to bring those to the surface and be more explicit right?

**Comment by MattPereira** [comment]
Definitely agree with modularizing the examples. Might be good to outline the folder/file structure as starting point.

Not sure best way to handle custom vs smart path given the different approval options. Kinda gross to repeat

Feel free to edit:

- 📁 examples
  - 📁 swaps
    - 📄 query.ts
    - 📁 withApproval
      - 📄 customPath.ts
      - 📄 smartPath.ts
    - 📁 withSignature
      - 📄 customPath.ts
      - 📄 smartPath.ts
  - 📁 approvals
    - 📁 v2
    - 📁 v3

**Comment by MattPereira** [comment]
While viem's `client.impersonateAccount` can simulate transactions on a fork, it does not seem to be able to `.signTypedData`, because signatures require a private key no matter what

I think Bruno did this in the `PermitHelper` by using the private key associated with the default viem test addresses
